### PR TITLE
Add a tip for vesktop users trying to install custom plugins

### PR DESCRIPTION
**Pull request by Pandoroeo**
Pretty much the title, it's just a small clarification I felt was needed.

### CODE REVIEW

**Comment by Vendicated** [comment]
this is just wrong. you always put them in src and build... dist is the folder where output artifacts are created by building

**Comment by Pandoroeo** [comment]
> this is just wrong. you always put them in src and `pnpm build`... dist is the folder where output artifacts are created by building

Really? For me it only started to work when I placed it to the dist folder.

**Comment by Sqaaakoi** [comment]
sounds like unintended behaviour

**Comment by Vendicated** [comment]
then you did it wrong.

**Pull request closed without merging**
